# .github/workflows/ci.yml
name: Run Jupyter Notebooks

on:
  push:
    paths:
      - '**.ipynb'
      - '**/ci.yml'
      - '**/requirements.txt'
  pull_request:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r notebooks/Data-Visualization/requirements.txt

      - name: Run notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute notebooks/Data-Visualization/visualization.ipynb --output executed_notebook.ipynb
